apiVersion: v1
kind: Pod
metadata:
  name: ny-taxi-exec
  namespace: big-data
spec:
  nodeSelector:
    nodegroup: x86-cpu
    type: karpenter
  initContainers:
    - name: volume-permission
      image: public.ecr.aws/docker/library/busybox
      command: ["sh", "-c", "mkdir /data1; chown -R 999:1000 /data1"]
  containers:
    - name: spark-kubernetes-executor