Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
  S3Object:
    Type: AWS::CloudFormation::CustomResource
    Properties:
      ServiceToken: !GetAtt LambdaFunction.Arn
      S3Bucket: !Ref S3Bucket
      S3ObjectKey: index.html
      S3ObjectBody: |
        <!DOCTYPE html>
        <html lang="ko">
        <head>
          <meta charset="UTF-8">
          <title>안녕하세요</title>
        </head>
        <body>
          <h1>안녕하세요</h1>
        </body>
        </html>
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.14
      Handler: index.handler
      Role: !GetAtt LambdaFunctionIamRole.Arn
      Timeout: 900
      MemorySize: 256
      Code:
        ZipFile: |
          import json
          import time
          import cfnresponse
          import boto3
          s3 = boto3.client("s3")
          s3_resource = boto3.resource("s3")
          def handler(event, context):
            print(f"Event : {json.dumps(event)}")
            response_data = {}
            try:
              request_type = event["RequestType"]
              s3_bucket = event["ResourceProperties"]["S3Bucket"]
              s3_object_key = event["ResourceProperties"]["S3ObjectKey"]
              s3_object_body = event["ResourceProperties"]["S3ObjectBody"]
              if request_type == "Create":
                s3.put_object(Bucket=s3_bucket, Key=s3_object_key, Body=s3_object_body.encode("utf-8"))
                response_data["Message"] = "Custom Resource Created"
              elif request_type == "Update":
                s3.put_object(Bucket=s3_bucket, Key=s3_object_key, Body=s3_object_body.encode("utf-8"))
                response_data["Message"] = "Custom Resource Updated"
              elif request_type == "Delete":
                s3.delete_object(Bucket=s3_bucket, Key=s3_object_key)
                response_data["Message"] = "Custom Resource Deleted"
              cfnresponse.send(event, context, cfnresponse.SUCCESS, response_data)
            except Exception as e:
              response_data["Message"] = "Error"
              cfnresponse.send(event, context, cfnresponse.FAILED, response_data, reason=str(e))
  LambdaFunctionIamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - !Sub arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3Access
          PolicyDocument: 
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:DeleteObject
                Resource: !Sub ${S3Bucket.Arn}/*
        # - !Sub arn:${AWS::Partition}:iam::aws:policy/AmazonS3FullAccess