AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Lambda Kakao AI Chatbot

Mappings:
  ResourceMap:
    CallbackLambdaFunction: 
      Name: bedrock-drawing-callback-lambda

Globals:
  Function:
    Timeout: 480
    MemorySize: 1024
    Environment:
      Variables:
        CALLBACK_LAMBDA_FUNCTION_NAME: !FindInMap [ResourceMap, CallbackLambdaFunction, Name]
        TEXT_TO_IMAGE_S3_BUCKET_NAME : !Ref TextToImageS3Bucket
        AWS_REGION_NAME : !Ref AWS::Region

Resources:
  KakaoChatbotLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.12
      CodeUri: ./src
      Description: Kakao Chatbot Function
      Role: !GetAtt KakaoChatbotLambdaFunctionRole.Arn
      Events:
        Skill:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayRestApi
            Path: /kakao
            Method: ANY

  KakaoChatbotLambdaFunctionRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service: lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: KakaoChatbotIamPolicy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - lambda:InvokeFunction
                    - lambda:InvokeAsync
                  Resource: "*"
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource: "*"
  
  ApiGatewayRestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: v1
      OpenApiVersion: '2.0'
      Auth:
        ApiKeyRequired: true
        UsagePlan:
          CreateUsagePlan: PER_API

  CallbackLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !FindInMap [ResourceMap, CallbackLambdaFunction, Name]
      Handler: callback.lambda_handler
      Runtime: python3.12
      CodeUri: ./src
      Layers:
        - !Ref LambdaLayer
      Description: Kakao Chatbot Callback Function
      Role: !GetAtt CallbackLambdaFunctionRole.Arn
  
  CallbackLambdaFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CallbackIamPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                  - lambda:InvokeAsync
                Resource: "*"
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
              - Effect: Allow
                Action:
                  - bedrock:*
                  - translate:*
                  - s3:*
                Resource: "*"
  
  LambdaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: LambdaLayer
      Description: Python Lambda Layer
      ContentUri: ./layer.zip
      CompatibleRuntimes:
        - python3.12
  
  TextToImageS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
  
  TextToImageS3BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref TextToImageS3Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub "${TextToImageS3Bucket.Arn}/*"

Outputs:
  KakaoChatbotFunction:
    Description: "Kakao Chatbot Function ARN"
    Value: !GetAtt KakaoChatbotLambdaFunction.Arn
  KakaoChatbotFunctionRole:
    Description: "IAM Role for Kakao Chatbot Function"
    Value: !GetAtt KakaoChatbotLambdaFunctionRole.Arn
  CallbackFunction:
    Description: "Kakao Chatbot Callback Function ARN"
    Value: !GetAtt CallbackLambdaFunction.Arn
  CallbackFunctionRole:
    Description: "IAM Role for Kakao Chatbot Callback Function"
    Value: !GetAtt CallbackLambdaFunctionRole.Arn