apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: max
spec:
  template:
    metadata: {}
    spec:
      nodeClassRef:
        group: eks.amazonaws.com
        kind: NodeClass
        name: default
      requirements:
        # https://docs.aws.amazon.com/eks/latest/userguide/create-node-pool.html#_sample_nodepool
        # Operators { In, NotIn, Exists, DoesNotExist, Gt, Lt } are supported.
        - key: "topology.kubernetes.io/zone"
          operator: In
          values: ["us-east-1a", "us-east-1b"]
        # - key: "node.kubernetes.io/instance-type"
        #   operator: In
        #   values: ["g4dn.8xlarge"]
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["on-demand"]
        # - key: "eks.amazonaws.com/instance-hypervisor"
        #   operator: In
        #   values: ["nitro"]
        - key: "eks.amazonaws.com/compute-type"
          operator: In
          values: ["auto"]
        # - key: "eks.amazonaws.com/instance-encryption-in-transit-supported"
        #   operator: In
        #   values: ["false"]
        - key: "eks.amazonaws.com/instance-category"
          operator: In
          values: ["t"]
        - key: "eks.amazonaws.com/instance-generation"
          operator: In
          values: ["3"]
        # - key: "eks.amazonaws.com/instance-family"
        #   operator: In
        #   values: ["g4dn"]
        # - key: "eks.amazonaws.com/instance-size"
        #   operator: In
        #   values: ["8xlarge"]
        - key: "eks.amazonaws.com/instance-cpu"
          operator: Lt
          values: ["20"]
        # - key: "eks.amazonaws.com/instance-cpu-manufacturer"
        #   operator: In
        #   values: ["aws"]
        - key: "eks.amazonaws.com/instance-memory"
          operator: Lt
          values: ["12000"]
        # - key: "eks.amazonaws.com/instance-ebs-bandwidth"
        #   operator: Lt
        #   values: ["12000"]
        # - key: "eks.amazonaws.com/instance-network-bandwidth"
        #   operator: Lt
        #   values: ["12000"]
        # - key: "eks.amazonaws.com/instance-gpu-name"
        #   operator: In
        #   values: ["t4"]
        # - key: "eks.amazonaws.com/instance-gpu-manufacturer"
        #   operator: In
        #   values: ["nvidia"]
        # - key: "eks.amazonaws.com/instance-gpu-count"
        #   operator: In
        #   values: ["1"]
        # - key: "eks.amazonaws.com/instance-gpu-memory"
        #   operator: In
        #   values: ["16384"]
        # - key: "eks.amazonaws.com/instance-local-nvme"
        #   operator: In
        #   values: ["900"]