apiVersion: apps/v1
kind: Deployment
metadata:
  name: efs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: efs
  template:
    metadata:
      labels:
        app: efs
    spec:
      containers:
      - name: app
        image: rockylinux:8
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo $(date -u) >> /data/out; sleep 5; done"]
        volumeMounts:
        - name: persistent-storage
          mountPath: /data
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: efs-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi