kind: ConfigMap
apiVersion: v1
metadata:
  name: aws-logging
  namespace: aws-observability
data:
  flb_log_cw: 'true'
  filters.conf: |
    [FILTER]
        Name parser
        Match kube.*
        Key_name log
        Parser crio
    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log On
        Keep_Log Off
        Buffer_Size 0
        Kube_Meta_Cache_TTL 300s
    [FILTER]
        Name grep
        Match kube.*
        Exclude $kubernetes['pod_name'] deploy2-*
  output.conf: |
    [OUTPUT]
        Name cloudwatch_logs
        Match kube.*
        Retry_Limit 10
        region us-east-1
        log_group_name /eks/fargate/
        log_stream_prefix log-
        log_retention_days 60
        auto_create_group true
  parsers.conf: |
    [PARSER]
        Name crio
        Format Regex
        Regex ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>P|F) (?<log>.*)$
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z