apiVersion: eks.amazonaws.com/v1
kind: NodeClass
metadata:
  name: custom
spec:
  ephemeralStorage:
    iops: 3000
    size: 80Gi
    throughput: 125
  networkPolicy: DefaultAllow
  networkPolicyEventLogs: Disabled
  role: AmazonEKSAutoNodeRole
  securityGroupSelectorTerms:
  - id: sg-blabla
  snatPolicy: Random
  subnetSelectorTerms:
  - id: subnet-blabla
  - id: subnet-blabla
  - id: subnet-blabla
  - id: subnet-blabla