version: 0.0
os: linux
files:
  - source: ./src/__pycache__/app.pyc
    destination: /home/ec2-user
hooks:
  ApplicationStart:
    - location: ./scripts/start_server.sh
      timeout: 300
      runas: root