version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - pip3 install flask
  build:
    commands:
      - python3 -m compileall ./src/app.py
      - mv src/__pycache__/app.cpython-39.pyc src/__pycache__/app.pyc
artifacts:
  files:
    - ./src/__pycache__/app.pyc
    - appspec.yml
    - scripts/start_server.sh