CREATE DATABASE IF NOT EXISTS day1;

USE day1;

CREATE TABLE IF NOT EXISTS green (
    uuid VARCHAR(8) PRIMARY KEY,
    x VARCHAR(255) NOT NULL,
    y DOUBLE NOT NULL
);

CREATE TABLE IF NOT EXISTS red (
    uuid VARCHAR(8) PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);
