Transform: AWS::LanguageExtensions
Parameters:
  OrganizationRootId:
    Description: Organization Root ID if it exists
    Type: String
    AllowedPattern: ^(r-[a-z0-9]{4,32})?$
    ConstraintDescription: A string that begins with "r-" followed by 4 to 32 lowercase letters or digits
  AuditAccount:
    Description: Audit Account ID
    Type: String
    AllowedPattern: ^\d{12}$
    ConstraintDescription: 12-digit AWS Account ID
  LogArchiveAccount:
    Description: Log Archive Account ID
    Type: String
    AllowedPattern: ^\d{12}$
    ConstraintDescription: 12-digit AWS Account ID
  LandingZoneVersion:
    Description: Landing Zone Version
    Type: String
    Default: 4.0
    AllowedPattern: ^\d+.\d+
    ConstraintDescription: X.X (Example 2.1, 3.3, 4.0, ...)
Conditions:
  OrganizationRootIdNotEmpty: !Not [!Equals [!Ref OrganizationRootId, ""]]
  OrganizationRootIdEmpty: !Equals [!Ref OrganizationRootId, ""]


Resources:
  Organization:
    Type: AWS::Organizations::Organization
    Condition: OrganizationRootIdEmpty
    Properties:
      FeatureSet: ALL # or CONSOLIDATED_BILLING
  
  JohanOU:
    Type: AWS::Organizations::OrganizationalUnit
    Properties:
      Name: Johan
      ParentId: !If
        - OrganizationRootIdNotEmpty
        - !Ref OrganizationRootId
        - !GetAtt Organization.RootId

  ControlTowerLandingZone:
    Type: AWS::ControlTower::LandingZone
    Properties:
      Manifest:
        # https://docs.aws.amazon.com/ko_kr/controltower/latest/userguide/lz-api-launch.html#w2aac15c17c17b5
        {
          "accessManagement": {
            "enabled": true
          },
          "securityRoles": {
            "accountId": !Ref AuditAccount,
            "enabled": true
          },
          "backup": {
            "enabled": false
          },
          "governedRegions": [
            !Ref AWS::Region
          ],
          "config": {
            "accountId": !Ref AuditAccount,
            "configurations": {
              "loggingBucket": {
                "retentionDays": 365
              },
              "accessLoggingBucket": {
                "retentionDays": 3650
              }
            },
            "enabled": true
          },
          "centralizedLogging": {
            "accountId": !Ref LogArchiveAccount,
            "configurations": {
              "loggingBucket": {
                "retentionDays": 365
              },
              "accessLoggingBucket": {
                "retentionDays": 3650
              }
            },
            "enabled": true
          }
        }
      RemediationTypes: 
        - INHERITANCE_DRIFT
      Version: !Ref LandingZoneVersion
      Tags: 
        - Key: x
          Value: y
  
  ControlTowerControl:
    Type: AWS::ControlTower::EnabledControl
    Properties:
      # [CT.MULTISERVICE.PV.1] Deny access to AWS based on the requested AWS Region for an organizational unit
      # Disallows access to unlisted operations in global and regional services outside of the specified Regions for an organizational unit.
      # https://aws.amazon.com/ko/blogs/tech/enable-amazon-bedrock-cross-region-inference-in-multi-account-environments/
      ControlIdentifier: arn:aws:controlcatalog:::control/ka8e3pkqefnjsxuyc26ji580
      TargetIdentifier: !GetAtt JohanOU.Arn
      Parameters:
        - Key: AllowedRegions
          Value: 
            - !Ref AWS::Region
        - Key: ExemptedActions
          Value:
            - besrock:*
        # - Key: ExemptedPrincipalArns
        #   Value:
        #     - 
  
  # Resource handler returned message: "To change the enablement and configuration of this baseline, you must modify your landing zone settings. (Service: ControlTower, Status Code: 400, Request ID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx) (SDK Attempt Count: 1)" (RequestToken: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx, HandlerErrorCode: InvalidRequest)
  # ControlTowerBaseline:
  #   Type: AWS::ControlTower::EnabledBaseline
  #   Properties:
  #     # aws controltower list-baselines
  #     # AuditBaseline
  #     # Sets up resources to monitor security and compliance of accounts in your organization.
  #     BaselineIdentifier: arn:aws:controltower:ap-northeast-2::baseline/4T4HA1KMO10S6311
  #     BaselineVersion: 5.0
  #     TargetIdentifier: !GetAtt JohanOU.Arn
  #     # Parameters: 
  #     #   - Key: String
  #     #     Value: String

Outputs:
  ControlTowerLandingZoneArn:
    Value: !GetAtt ControlTowerLandingZone.Arn
    Description: ControlTower LandingZone ARN
  ControlTowerLandingZoneIdentifier:
    Value: !GetAtt ControlTowerLandingZone.LandingZoneIdentifier
    Description: ControlTower LandingZone ID