apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: x86-cpu-karpenter
spec:
  template:
    metadata:
      labels:
        nodegroup: x86-cpu
        type: karpenter
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: x86-cpu-karpenter
      requirements:
        - key: karpenter.k8s.aws/instance-family
          operator: In
          values:
          - m5
        - key: karpenter.k8s.aws/instance-size
          operator: In
          values:
            - xlarge
            - 2xlarge
            - 4xlarge
            - 8xlarge
        - key: kubernetes.io/arch
          operator: In
          values:
            - amd64
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - spot
            - on-demand
  disruption:
    budgets:
    - nodes: 10%
    consolidateAfter: 300s
    consolidationPolicy: WhenEmpty
  limits:
    cpu: 1000
    memory: 1000Gi
---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: x86-cpu-karpenter
spec:
  amiFamily: Bottlerocket
  amiSelectorTerms:
  - alias: bottlerocket@latest
  blockDeviceMappings:
  - deviceName: /dev/xvda
    ebs:
      encrypted: true
      volumeSize: 100Gi
      volumeType: gp3
  - deviceName: /dev/xvdb
    ebs:
      encrypted: true
      volumeSize: 300Gi
      volumeType: gp3
  detailedMonitoring: true
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required
  subnetSelectorTerms:
    - id: subnet-xxxxxx
    - id: subnet-xxxxxx
  securityGroupSelectorTerms:
    - id: sg-xxxxxx
  instanceProfile: xxxxxx-KarpenterNodeInstanceProfile-xxxxxx
  # role: xxxxxx-KarpenterNodeIamRole-xxxxxx
  tags:
    Name: x86-cpu-karpenter